// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock/contract.go -package=mock_request
//

// Package mock_request is a generated GoMock package.
package mock_request

import (
	reflect "reflect"

	request "github.com/qreaqtor/wallet/pkg/api/handler/request"
	gomock "go.uber.org/mock/gomock"
)

// MockParams is a mock of Params interface.
type MockParams struct {
	ctrl     *gomock.Controller
	recorder *MockParamsMockRecorder
	isgomock struct{}
}

// MockParamsMockRecorder is the mock recorder for MockParams.
type MockParamsMockRecorder struct {
	mock *MockParams
}

// NewMockParams creates a new mock instance.
func NewMockParams(ctrl *gomock.Controller) *MockParams {
	mock := &MockParams{ctrl: ctrl}
	mock.recorder = &MockParamsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockParams) EXPECT() *MockParamsMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockParams) Get(key string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockParamsMockRecorder) Get(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockParams)(nil).Get), key)
}

// MockRequest is a mock of Request interface.
type MockRequest[In any] struct {
	ctrl     *gomock.Controller
	recorder *MockRequestMockRecorder[In]
	isgomock struct{}
}

// MockRequestMockRecorder is the mock recorder for MockRequest.
type MockRequestMockRecorder[In any] struct {
	mock *MockRequest[In]
}

// NewMockRequest creates a new mock instance.
func NewMockRequest[In any](ctrl *gomock.Controller) *MockRequest[In] {
	mock := &MockRequest[In]{ctrl: ctrl}
	mock.recorder = &MockRequestMockRecorder[In]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequest[In]) EXPECT() *MockRequestMockRecorder[In] {
	return m.recorder
}

// GetBody mocks base method.
func (m *MockRequest[In]) GetBody() (In, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBody")
	ret0, _ := ret[0].(In)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBody indicates an expected call of GetBody.
func (mr *MockRequestMockRecorder[In]) GetBody() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBody", reflect.TypeOf((*MockRequest[In])(nil).GetBody))
}

// GetPath mocks base method.
func (m *MockRequest[In]) GetPath() request.Params {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPath")
	ret0, _ := ret[0].(request.Params)
	return ret0
}

// GetPath indicates an expected call of GetPath.
func (mr *MockRequestMockRecorder[In]) GetPath() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPath", reflect.TypeOf((*MockRequest[In])(nil).GetPath))
}

// GetQuery mocks base method.
func (m *MockRequest[In]) GetQuery() request.Params {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuery")
	ret0, _ := ret[0].(request.Params)
	return ret0
}

// GetQuery indicates an expected call of GetQuery.
func (mr *MockRequestMockRecorder[In]) GetQuery() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuery", reflect.TypeOf((*MockRequest[In])(nil).GetQuery))
}
