// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock/contract.go -package=mock_updatewallet
//

// Package mock_updatewallet is a generated GoMock package.
package mock_updatewallet

import (
	context "context"
	reflect "reflect"

	entity "github.com/qreaqtor/wallet/internal/domain/entity"
	types "github.com/qreaqtor/wallet/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// Mockusecase is a mock of usecase interface.
type Mockusecase struct {
	ctrl     *gomock.Controller
	recorder *MockusecaseMockRecorder
	isgomock struct{}
}

// MockusecaseMockRecorder is the mock recorder for Mockusecase.
type MockusecaseMockRecorder struct {
	mock *Mockusecase
}

// NewMockusecase creates a new mock instance.
func NewMockusecase(ctrl *gomock.Controller) *Mockusecase {
	mock := &Mockusecase{ctrl: ctrl}
	mock.recorder = &MockusecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockusecase) EXPECT() *MockusecaseMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *Mockusecase) Run(ctx context.Context, walletID types.WalletID, action types.Action, amount types.Amount) (entity.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, walletID, action, amount)
	ret0, _ := ret[0].(entity.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Run indicates an expected call of Run.
func (mr *MockusecaseMockRecorder) Run(ctx, walletID, action, amount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*Mockusecase)(nil).Run), ctx, walletID, action, amount)
}
