// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock/contract.go -package=mock_getwallet
//

// Package mock_getwallet is a generated GoMock package.
package mock_getwallet

import (
	context "context"
	reflect "reflect"

	entity "github.com/qreaqtor/wallet/internal/domain/entity"
	types "github.com/qreaqtor/wallet/internal/domain/types"
	gomock "go.uber.org/mock/gomock"
)

// MockwalletRepo is a mock of walletRepo interface.
type MockwalletRepo struct {
	ctrl     *gomock.Controller
	recorder *MockwalletRepoMockRecorder
	isgomock struct{}
}

// MockwalletRepoMockRecorder is the mock recorder for MockwalletRepo.
type MockwalletRepoMockRecorder struct {
	mock *MockwalletRepo
}

// NewMockwalletRepo creates a new mock instance.
func NewMockwalletRepo(ctrl *gomock.Controller) *MockwalletRepo {
	mock := &MockwalletRepo{ctrl: ctrl}
	mock.recorder = &MockwalletRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockwalletRepo) EXPECT() *MockwalletRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockwalletRepo) GetByID(ctx context.Context, walletID types.WalletID) (entity.Wallet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, walletID)
	ret0, _ := ret[0].(entity.Wallet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockwalletRepoMockRecorder) GetByID(ctx, walletID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockwalletRepo)(nil).GetByID), ctx, walletID)
}
