// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -source=contract.go -destination=mock/contract.go -package=mock_response
//

// Package mock_response is a generated GoMock package.
package mock_response

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSuccess is a mock of Success interface.
type MockSuccess[Out any] struct {
	ctrl     *gomock.Controller
	recorder *MockSuccessMockRecorder[Out]
	isgomock struct{}
}

// MockSuccessMockRecorder is the mock recorder for MockSuccess.
type MockSuccessMockRecorder[Out any] struct {
	mock *MockSuccess[Out]
}

// NewMockSuccess creates a new mock instance.
func NewMockSuccess[Out any](ctrl *gomock.Controller) *MockSuccess[Out] {
	mock := &MockSuccess[Out]{ctrl: ctrl}
	mock.recorder = &MockSuccessMockRecorder[Out]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSuccess[Out]) EXPECT() *MockSuccessMockRecorder[Out] {
	return m.recorder
}

// NoContent mocks base method.
func (m *MockSuccess[Out]) NoContent() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NoContent")
}

// NoContent indicates an expected call of NoContent.
func (mr *MockSuccessMockRecorder[Out]) NoContent() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NoContent", reflect.TypeOf((*MockSuccess[Out])(nil).NoContent))
}

// OK mocks base method.
func (m *MockSuccess[Out]) OK(arg0 Out) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OK", arg0)
}

// OK indicates an expected call of OK.
func (mr *MockSuccessMockRecorder[Out]) OK(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OK", reflect.TypeOf((*MockSuccess[Out])(nil).OK), arg0)
}

// Raw mocks base method.
func (m *MockSuccess[Out]) Raw(arg0 []byte) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Raw", arg0)
}

// Raw indicates an expected call of Raw.
func (mr *MockSuccessMockRecorder[Out]) Raw(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Raw", reflect.TypeOf((*MockSuccess[Out])(nil).Raw), arg0)
}

// MockError is a mock of Error interface.
type MockError struct {
	ctrl     *gomock.Controller
	recorder *MockErrorMockRecorder
	isgomock struct{}
}

// MockErrorMockRecorder is the mock recorder for MockError.
type MockErrorMockRecorder struct {
	mock *MockError
}

// NewMockError creates a new mock instance.
func NewMockError(ctrl *gomock.Controller) *MockError {
	mock := &MockError{ctrl: ctrl}
	mock.recorder = &MockErrorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockError) EXPECT() *MockErrorMockRecorder {
	return m.recorder
}

// BadRequest mocks base method.
func (m *MockError) BadRequest(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BadRequest", err)
}

// BadRequest indicates an expected call of BadRequest.
func (mr *MockErrorMockRecorder) BadRequest(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BadRequest", reflect.TypeOf((*MockError)(nil).BadRequest), err)
}

// InternalError mocks base method.
func (m *MockError) InternalError(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "InternalError", err)
}

// InternalError indicates an expected call of InternalError.
func (mr *MockErrorMockRecorder) InternalError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InternalError", reflect.TypeOf((*MockError)(nil).InternalError), err)
}

// NotFound mocks base method.
func (m *MockError) NotFound(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NotFound", err)
}

// NotFound indicates an expected call of NotFound.
func (mr *MockErrorMockRecorder) NotFound(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NotFound", reflect.TypeOf((*MockError)(nil).NotFound), err)
}

// TooManyRequests mocks base method.
func (m *MockError) TooManyRequests(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TooManyRequests", err)
}

// TooManyRequests indicates an expected call of TooManyRequests.
func (mr *MockErrorMockRecorder) TooManyRequests(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TooManyRequests", reflect.TypeOf((*MockError)(nil).TooManyRequests), err)
}
