openapi: 3.0.3
info:
  title: Wallet Service API
  version: "1.0.0"
  description:
    REST API для управления балансом кошельков.
    Позволяет пополнять или снимать средства, а также получать текущий баланс кошелька.

components:
  schemas:
    WalletOperationRequest:
      type: object
      required:
        - walletId
        - operationType
        - amount
      properties:
        walletId:
          type: string
          format: uuid
          description: UUID кошелька
        operationType:
          type: string
          enum: [DEPOSIT, WITHDRAW]
          description: Тип операции (пополнение или снятие)
        amount:
          type: integer
          format: int64
          minimum: 0
          description: Сумма операции

    WalletBalanceResponse:
      type: object
      required:
        - walletId
        - balance
        - updatedAt
        - createdAt
      properties:
        walletId:
          type: string
          format: uuid
        balance:
          type: integer
          format: int64
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          description: HTTP-код ошибки
          example: 400
        message:
          type: string
          description: Описание ошибки
          example: "invalid request parameters"

  responses:
    BadRequest:
      description: Неверные данные запроса
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 400
            message: "invalid operation type or amount"

    NotFound:
      description: Кошелёк не найден
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 404
            message: "wallet not found"

    TooManyRequests:
      description: Превышено количество запросов
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 429
            message: "too many requests"

    InternalServerError:
      description: Внутренняя ошибка сервера
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            code: 500
            message: "internal server error"


paths:
  /api/v1/wallet:
    post:
      summary: Изменить баланс кошелька
      description: >
        Выполняет операцию пополнения (`DEPOSIT`) или снятия (`WITHDRAW`)
        средств с указанного кошелька.  
        Возвращает обновлённый баланс.
      operationId: updateWalletBalance
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletOperationRequest'
            example:
              walletId: "123e4567-e89b-12d3-a456-426614174000"
              operationType: "DEPOSIT"
              amount: 1000
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletBalanceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'

  /api/v1/wallets/{walletId}:
    get:
      summary: Получить баланс кошелька
      description: Возвращает текущий баланс кошелька по его UUID.
      operationId: getWalletBalance
      parameters:
        - name: walletId
          in: path
          required: true
          description: UUID кошелька
          schema:
            type: string
            format: uuid
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletBalanceResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '429':
          $ref: '#/components/responses/TooManyRequests'
        '500':
          $ref: '#/components/responses/InternalServerError'